### ISSUE TITLE
Week View UI

### ISSUE THREAD

**Issue by TrinaKat** [ucladevx/Bmaps-Frontend#256]
Create new events view that closely relates to UCLA's weekly quarter system. The official design may be worked on in parallel, so start with barebones template and apply design as possible.

### Overview:
Current Map view and a Monthly Calendar view:
![image](https://user-images.githubusercontent.com/17267100/48231572-77719500-e363-11e8-85ee-32fe581466b7.png)

Relevant UI from Google Calendar:
![image](https://user-images.githubusercontent.com/17267100/48231639-ad167e00-e363-11e8-9101-0bf2b2acf334.png)

Concept: add a Week view that follows UCLA's academic calendar (e.g. Week 0, Week 1, ...) for displaying events on a weekly basis. Allows us to display more events and more event info than calendar. Users are still able to plan ahead.

We can discuss this further, but I believe a static view of Sunday -> Monday -> ... -> Saturday makes the most sense (e.g. does not rotate as days progress). 

MVP goals:
- [x] Add separate Week view (should be interchangeable with calendar/map views)
- [x] Should block out the time period of an event. Handle overlapping events.
- [x] Hook up Week view with filters (filters should be identical to calendar filters, no extra sidebar configuration required)

Future goals:
- Options to configure colors per category
- Option to hide events? Or just option to show favorited events. Dependent on user accounts.
- Configure hour limits of each day
- Import MyUCLA calendar (potentially for calendar UI as well?). Dependent on user accounts.

**Comment by TrinaKat** [comment]
http://preview.codecanyon.net/item/tiva-timetable/full_screen_preview/17916231?ref=andy4321

https://fullcalendar.io/

**Comment by TrinaKat** [comment]
- Follow https://fullcalendar.io/ style
- Should have full range of 12 am - 12 am, but only like 8 am - midnight should be visible in a scrollable box.
- Events should be restricted to 15 min intervals
- Horizontal lines by the hour
- Popups over events for more info
- Add mock for all-day event, probably won't support these except as additional feature far in the future

**Comment by dhs766** [comment]
- Today's date text colour should be the Mappening blue. 
- Days that are selected or hovered over should grey out (just like in calendar).
- Week view is an option within "Calendar", users can interchange between week view and month view on "Calendar". There should be a switch button (same look as calendar/map button) between month and week view (right corner). Left corner of week view would state the UCLA school week (ex. Week 9)
- Think of how bookmarked events would look on week view.
