### ISSUE TITLE
Small Bugs

### ISSUE THREAD

**Issue by TrinaKat** [ucladevx/Bmaps-Frontend#286]
- Make <> arrows a static location (shifts depending on width of surrounded text)
- Filters text is not centered vertically
- Month filters are capitalized
- Month date filters cut off the date
- Week view has odd spacing under date number
- Week view does not start at 7am
- Calendar category filters should be multiselect
- Mobile views in general lol (responsive design for week view pls)

**Comment by wfehrnstrom** [comment]
Steps to reproduce: open up web app on mobile and go to tomorrow, or a day with any events. Click on event. You now get a double header bar, which has a lower z-index than the event picture.

**Comment by wfehrnstrom** [comment]
Errant Event behavior: this apperars to be a backend issue, because the events themselves are displaying properly. Multiple of the same event are showing on the map. We should get to the bottom of the app state that is causing this to occur: 
<img width="1280" alt="Screen Shot 2019-05-03 at 4 08 12 PM" src="https://user-images.githubusercontent.com/10459837/57169796-c6056680-6dbd-11e9-8ab3-b9c671d3408f.png">

**Comment by wfehrnstrom** [comment]
Week not capitalized. Not sure if this is a feature or a bug.
<img width="531" alt="Screen Shot 2019-05-03 at 4 14 23 PM" src="https://user-images.githubusercontent.com/10459837/57169949-9b67dd80-6dbe-11e9-98f0-f906feddedfd.png">

**Comment by wfehrnstrom** [comment]
Event Categories display as they probably are in the code, perhaps we should define a map of user friendly names that map to each of these categories?
<img width="209" alt="Screen Shot 2019-05-03 at 4 15 55 PM" src="https://user-images.githubusercontent.com/10459837/57169995-d8cc6b00-6dbe-11e9-9558-b611fbf5a4d3.png">

**Comment by wfehrnstrom** [comment]
Should we keep month names full for above filter portion?
<img width="210" alt="Screen Shot 2019-05-03 at 4 20 17 PM" src="https://user-images.githubusercontent.com/10459837/57170113-7031be00-6dbf-11e9-80ef-7c7e08479a71.png">

**Comment by wfehrnstrom** [comment]
No active style applied on filter elements being active for the button that toggles the filter. Not a bug, but a quality of life improvement.
<img width="640" alt="Screen Shot 2019-05-03 at 4 22 04 PM" src="https://user-images.githubusercontent.com/10459837/57170163-d74f7280-6dbf-11e9-8b7a-001c51f665ea.png">

**Comment by tanzeelak** [comment]
i'm gonna work on this: 
- Make <> arrows a static location (shifts depending on width of surrounded text)
